/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package Vista;
import Controlador.clsSeguridad;
import Controlador.clsBitacora;
import Controlador.clsPeliculas;
import Controlador.clsUsuarioConectado;
import Modelo.BitacoraDAO;
import Modelo.Conexion;
import Modelo.PeliculasDAO;
import java.util.List;
import javax.swing.table.DefaultTableModel;
import java.io.File;
import java.sql.Connection;
import java.util.HashMap;
import java.util.HashSet;
import java.util.Map;
import java.util.Set;
import javax.swing.JOptionPane;
/**
 *
 * @author Angel R
 */
public class frmMantenimientoPeliculas extends javax.swing.JInternalFrame {

    /**
     * Creates new form frmMantenimientoPeliculas
     */
    public frmMantenimientoPeliculas() {
        initComponents();
        llenadoDeTablas();
    }
    
    private clsBitacora crearBitacora(String accion) {
    clsBitacora bitacora = new clsBitacora();

    try {
        BitacoraDAO dao = new BitacoraDAO();

        // Usuario conectado (este era tu error principal)
        bitacora.setUsucodigo(777);
        int usuario = 777; // valor por defecto

        try {
        usuario = clsUsuarioConectado.getUsuId();
        } catch (Exception e) {
    System.out.println("Usuario no definido, usando default");
    }

bitacora.setUsucodigo(usuario);

        // Código de aplicación (puedes dejar fijo si no tienes sistema de apps)
        bitacora.setAplcodigo(777);

        // Fecha actual
        bitacora.setBitfecha(dao.fechaActual());

        // IP y nombre del equipo
        bitacora.setBitip(java.net.InetAddress.getLocalHost().getHostAddress());
        bitacora.setBitequipo(java.net.InetAddress.getLocalHost().getHostName());

        // Acción
        bitacora.setBitaccion(accion);

    } catch (Exception e) {
        e.printStackTrace();
    }

    return bitacora;
}
    
   public void llenadoDeTablas() {
    DefaultTableModel modelo = new DefaultTableModel();
    modelo.addColumn("Id Pelicula");
    modelo.addColumn("Nombre ");
    modelo.addColumn("Clasificación");
    modelo.addColumn("Genero");
    modelo.addColumn("Subtitulado");
    modelo.addColumn("Idioma");
    modelo.addColumn("Precio");

    tablaPeliculas.setModel(modelo);

    PeliculasDAO dao = new PeliculasDAO();
    clsBitacora bitacora = crearBitacora("Consulta peliculas");
    List<clsPeliculas> listaPeliculas = dao.obtenerPeliculas(bitacora);

    String[] dato = new String[7];
    for (clsPeliculas p : listaPeliculas) {
        dato[0] = String.valueOf(p.getIdPeliculas());
        dato[1] = p.getNombre();
        dato[2] = p.getClasificacion();
        dato[3] = p.getGenero();
        dato[4] = p.getSubtitulado();
        dato[5] = p.getIdioma();
        dato[6] = String.valueOf(p.getPrecio());
        modelo.addRow(dato);
    }
    }
public void limpiarTextos()
    {
        txtCodigo.setText("");
        txtNombre.setText("");
        txtClasificacion.setText(""); 
        txtGenero.setText(""); 
        txtSubtitulado.setText(""); 
        txtIdioma.setText(""); 
        txtPrecio.setText(""); 
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnRegistrar = new javax.swing.JButton();
        btnModificar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnLimpiar = new javax.swing.JButton();
        txtBuscar = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        btnBuscar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtCodigo = new javax.swing.JTextField();
        txtNombre = new javax.swing.JTextField();
        txtClasificacion = new javax.swing.JTextField();
        txtGenero = new javax.swing.JTextField();
        txtSubtitulado = new javax.swing.JTextField();
        txtIdioma = new javax.swing.JTextField();
        txtPrecio = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaPeliculas = new javax.swing.JTable();

        setClosable(true);
        setTitle("Mantenimiento Peliculas");

        btnRegistrar.setText("Registrar");
        btnRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarActionPerformed(evt);
            }
        });

        btnModificar.setText("Modificar");
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });

        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        btnLimpiar.setText("Limpiar");
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setText("ID A BUSCAR");

        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        jLabel2.setText("ID");

        jLabel3.setText("NOMBRE");

        jLabel4.setText("CLASIFICACION");

        jLabel5.setText("GENERO");

        jLabel6.setText("SUBTITULADO");

        jLabel7.setText("IDIOMA");

        jLabel8.setText("PRECIO");

        txtNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel9.setText("Peliculas");

        tablaPeliculas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "NOMBRE", "CLASIFICACION", "GENERO", "SUBTITULADO", "IDIOMA", "PRECIO"
            }
        ));
        jScrollPane1.setViewportView(tablaPeliculas);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnBuscar)
                    .addComponent(btnLimpiar)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(48, 48, 48)
                                .addComponent(txtCodigo))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtPrecio))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtIdioma))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtSubtitulado))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtGenero))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtClasificacion))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 651, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel1)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(txtBuscar))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(btnRegistrar)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(btnModificar)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(btnEliminar))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtClasificacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtGenero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtSubtitulado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtIdioma, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txtPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRegistrar)
                    .addComponent(btnModificar)
                    .addComponent(btnEliminar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnLimpiar)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(1, 1, 1)
                .addComponent(btnBuscar)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(237, 237, 237))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
limpiarTextos();
        habilitarBotones();
    }                                          
    
    public void habilitarBotones()
    {
        btnRegistrar.setEnabled(true);
        btnModificar.setEnabled(true);
        btnEliminar.setEnabled(true);
    }
    public void desHabilitarBotones()
    {
        btnRegistrar.setEnabled(false);
        btnModificar.setEnabled(false);
        btnEliminar.setEnabled(false);
    }    
    public void esperar5min(){
        try {
            //Ponemos a "Dormir" el programa durante los minutos que querramos
            Thread.sleep(5*60*1000);
        } catch (Exception e) {
            System.out.println(e);}
      
    }//GEN-LAST:event_btnLimpiarActionPerformed

    private void txtNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        // TODO add your handling code here:
        if(txtCodigo.getText().isEmpty()){
        JOptionPane.showMessageDialog(null, "Ingrese un código");
        return;
    }

    clsPeliculas peliculas = new clsPeliculas();
    peliculas.setIdPeliculas(Integer.parseInt(txtCodigo.getText()));

    PeliculasDAO dao = new PeliculasDAO();
    clsBitacora bitacora = crearBitacora("Eliminar perfil");
dao.eliminarPeliculas(peliculas, bitacora);

    JOptionPane.showMessageDialog(null, "Peliculas eliminado");

    llenadoDeTablas();
    limpiarTextos();
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarActionPerformed
        // TODO add your handling code here:
         if(txtCodigo.getText().isEmpty() || txtNombre.getText().isEmpty()|| txtClasificacion.getText().isEmpty()|| txtGenero.getText().isEmpty()|| txtSubtitulado.getText().isEmpty()|| txtIdioma.getText().isEmpty()|| txtPrecio.getText().isEmpty()){
    JOptionPane.showMessageDialog(null, "Complete los campos");
    return;
    } 
    
    clsPeliculas peliculas = new clsPeliculas();
    peliculas.setIdPeliculas(Integer.parseInt(txtCodigo.getText()));
    peliculas.setNombre(txtNombre.getText());
    peliculas.setClasificacion(txtClasificacion.getText());
    peliculas.setGenero(txtGenero.getText());
    peliculas.setSubtitulado(txtSubtitulado.getText());
    peliculas.setIdioma(txtIdioma.getText());
    peliculas.setPrecio(Double.parseDouble(txtPrecio.getText()));
    

    PeliculasDAO dao = new PeliculasDAO();
    clsBitacora bitacora = crearBitacora("Insertar pelicula");
    dao.insertarPeliculas(peliculas, bitacora);

    JOptionPane.showMessageDialog(null, "Pelicula registrado");
    
    

    llenadoDeTablas();
    limpiarTextos();
                       
    }//GEN-LAST:event_btnRegistrarActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        // TODO add your handling code here:
        PeliculasDAO dao = new PeliculasDAO();
    if(txtBuscar.getText().isEmpty()){
    JOptionPane.showMessageDialog(null, "Ingrese un ID");
    return;
}
    int id = Integer.parseInt(txtBuscar.getText());

    clsBitacora bitacora = crearBitacora("Buscar pelicula");
clsPeliculas peliculas = dao.obtenerPeliculaPorId(id, bitacora);

    if(peliculas != null){
        txtCodigo.setText(String.valueOf(peliculas.getIdPeliculas()));
        txtNombre.setText(peliculas.getNombre());
        txtClasificacion.setText(peliculas.getClasificacion());
        txtGenero.setText(peliculas.getGenero());
        txtSubtitulado.setText(peliculas.getSubtitulado());
        txtIdioma.setText(peliculas.getIdioma());
        txtPrecio.setText(String.valueOf(peliculas.getPrecio()));
        
    }else{
        JOptionPane.showMessageDialog(null, "Pelicula no encontrado");
    }
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
        // TODO add your handling code here:
        if(txtCodigo.getText().isEmpty()){
    JOptionPane.showMessageDialog(null, "Seleccione un registro");
    return;
    }
    


    clsPeliculas peliculas = new clsPeliculas();
    peliculas.setIdPeliculas(Integer.parseInt(txtCodigo.getText()));
    peliculas.setNombre(txtNombre.getText());
    peliculas.setClasificacion(txtClasificacion.getText());
    peliculas.setGenero(txtGenero.getText());
    peliculas.setSubtitulado(txtSubtitulado.getText());
    peliculas.setIdioma(txtIdioma.getText());
    peliculas.setPrecio(Double.parseDouble(txtPrecio.getText()));
    

    PeliculasDAO dao = new PeliculasDAO();
    clsBitacora bitacora = crearBitacora("Modificar pelicula");
dao.actualizarPeliculas(peliculas, bitacora);

    JOptionPane.showMessageDialog(null, "Pelicula modificado");

    llenadoDeTablas();
    limpiarTextos();
    }//GEN-LAST:event_btnModificarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JButton btnModificar;
    private javax.swing.JButton btnRegistrar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablaPeliculas;
    private javax.swing.JTextField txtBuscar;
    private javax.swing.JTextField txtClasificacion;
    private javax.swing.JTextField txtCodigo;
    private javax.swing.JTextField txtGenero;
    private javax.swing.JTextField txtIdioma;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtPrecio;
    private javax.swing.JTextField txtSubtitulado;
    // End of variables declaration//GEN-END:variables
}
